#!/usr/bin/env python3
"""Pack the extension into a deterministic zip and embed it in the firmware as netmon/ytguard_pkg.h,
so the board can hand it out at http://netmon.local/extension/ytguard.zip. Run by ./build.sh compile."""
import hashlib, io, pathlib, zipfile

root = pathlib.Path(__file__).resolve().parent
files = sorted(p for p in root.rglob("*") if p.is_file() and p.name not in {"pack.py", ".DS_Store"} and "_metadata" not in p.parts)
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for p in files:
        info = zipfile.ZipInfo("ytguard/" + p.relative_to(root).as_posix(), date_time=(2026, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = 0o644 << 16
        z.writestr(info, p.read_bytes())
data = buf.getvalue()
sha = hashlib.sha256(data).hexdigest()[:16]
lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 24]) for i in range(0, len(data), 24)]
out = root.parent / "netmon" / "ytguard_pkg.h"
out.write_text(
    "#pragma once\n#include <Arduino.h>\n"
    "// GENERATED by extension/pack.py — do not edit. The browser extension, zipped, served by the board at\n"
    f"// /extension/ytguard.zip so laptops can install it without the repo. {len(data)} bytes, sha256 {sha}…\n"
    f"// Contents: {', '.join(p.relative_to(root).as_posix() for p in files)}\n"
    f"static const size_t YT_EXT_ZIP_LEN = {len(data)};\n"
    "static const uint8_t YT_EXT_ZIP[] PROGMEM = {\n  " + ",\n  ".join(lines) + "\n};\n")
print(f"ytguard_pkg.h: {len(files)} files, {len(data)} bytes zipped, sha256 {sha}")
