/*
  netmon — ESP32-S3 Internet Health Monitor + DNS ad blocker

  Every few seconds it probes your router and the internet, tracks latency,
  packet loss and outages, shows status on the onboard RGB LED, and serves a
  live dashboard on your LAN at http://netmon.local

  LED:  green = OK   amber = degraded   red = internet down (ISP)
        pink  = router unreachable      blue = connecting to Wi-Fi

  Board: ESP32-S3 (built-in USB-Serial/JTAG). No external libraries needed.
*/

#include <WiFi.h>
#include <WiFiClient.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <ArduinoOTA.h>
#include <HTTPClient.h>
#include <Preferences.h>
#include <time.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "secrets.h"
#include "dnsblock.h"
#include "ytguard.h"
#include "ytguard_pkg.h"   // the extension, zipped, served at /extension/ytguard.zip (generated by extension/pack.py)
#include "pages.h"         // INDEX_HTML (dashboard) and INSTALL_HTML (/extension)

// ---------------- Configuration ----------------
#ifndef HOSTNAME_STR
  #define HOSTNAME_STR "netmon"                       // overridden per board by secrets.h (./build.sh secrets)
#endif
#ifndef OTA_PASS
  #define OTA_PASS ""                                 // "" = no over-the-air updates
#endif
#ifndef PEER_BOARDS
  #define PEER_BOARDS ""                              // other boards shown on this dashboard, comma-separated IPs
#endif
static const char*    HOSTNAME          = HOSTNAME_STR;   // -> http://<HOSTNAME>.local
static const uint32_t PROBE_INTERVAL_MS = 5000;       // time between probe rounds
static const int32_t  PROBE_TIMEOUT_MS  = 1500;       // per-probe TCP connect timeout
static const int      DEGRADED_RTT_MS   = 150;        // avg public RTT above this = degraded
static const int      HISTORY_LEN       = 180;        // 180 x 5 s = 15 min of samples
static const int      MAX_OUTAGES       = 10;         // outages remembered (newest kept)
static const int      DOWN_DEBOUNCE     = 2;          // bad rounds in a row before "outage"
static const uint8_t  LED_BRIGHT        = 24;         // 0-255, keep it gentle
static const char*    TZ_INFO = "GMT0BST,M3.5.0/1,M10.5.0";   // Europe/London
#ifndef RGB_BUILTIN
  #define RGB_BUILTIN 48                              // onboard WS2812 on most S3 devkits
#endif

// ---------------- Probe targets ----------------
// A TCP connect to a known-open port measures one round trip, like a ping,
// but needs no ICMP library and proves a real service is answering.
struct Target { const char* name; IPAddress ip; uint16_t port; bool isGateway; };
static Target targets[] = {
  { "Router",     IPAddress(0, 0, 0, 0), 443, true  },   // filled in from DHCP gateway
  { "Cloudflare", IPAddress(1, 1, 1, 1),  53, false },
  { "Google",     IPAddress(8, 8, 8, 8),  53, false },
};
static const int NT = sizeof(targets) / sizeof(targets[0]);

// ---------------- State ----------------
enum NetState : uint8_t { ST_CONNECTING = 0, ST_UP, ST_DEGRADED, ST_DOWN_ISP, ST_DOWN_LAN };
static const char* STATE_NAMES[] = { "connecting", "up", "degraded", "down_isp", "down_lan" };
static const char* STATE_TEXT[]  = {
  "Connecting to Wi-Fi",
  "Internet OK",
  "Internet degraded",
  "Internet down — router is reachable, so it's likely the ISP",
  "Router unreachable — Wi-Fi or router problem",
};

struct Sample { int16_t rtt[NT]; int16_t dns; };
static Sample   hist[HISTORY_LEN];
static int      histHead = 0, histCount = 0;

struct Outage { time_t start; time_t end; uint8_t kind; };   // end == 0 -> ongoing
static Outage   outages[MAX_OUTAGES];
static int      outageCount = 0;

static volatile NetState state = ST_CONNECTING;
static int      lastRtt[NT];
static int      lastDns = -1;
static uint32_t okTotal[NT], failTotal[NT];
static uint32_t rounds = 0;
static int      downStreak = 0;
static bool     inOutage = false;
static time_t   firstDownEpoch = 0;
static time_t   bootEpoch = 0;
static SemaphoreHandle_t mtx;
static WebServer server(80);
static Preferences prefs;          // persisted settings (the "require the extension" switch)

// ---------------- YouTube guard (browser extension in ../extension) ----------------
// The extension fetches its rules from GET /api/yt/rules and reports what it removed to POST /api/yt/stats.
struct YtDevice { uint32_t ip; uint32_t blocked, skipped, hidden; uint32_t lastMs; };
static const int MAX_YT_DEVICES = 16;
static YtDevice ytDev[MAX_YT_DEVICES]; static int ytDevN = 0;
static uint32_t ytBlocked = 0, ytSkipped = 0, ytHidden = 0, ytReports = 0;   // only touched from the web server task

static long jsonInt(const String& body, const char* key) {   // tiny  "key": 123  extractor, no JSON library needed
  String k = String("\"") + key + "\"";
  int i = body.indexOf(k); if (i < 0) return 0;
  i = body.indexOf(':', i + k.length()); if (i < 0) return 0;
  i++; while (i < (int)body.length() && body[i] == ' ') i++;
  return body.substring(i).toInt();
}
static void cors() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.sendHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  server.sendHeader("Access-Control-Allow-Headers", "Content-Type");
}
static void ytRecord(uint32_t ip, long b, long s, long h) {
  if (b < 0 || s < 0 || h < 0 || b > 100000 || s > 100000 || h > 100000) return;   // garbage in, ignored
  ytBlocked += b; ytSkipped += s; ytHidden += h; ytReports++;
  int slot = -1, oldest = 0;
  for (int i = 0; i < ytDevN; i++) { if (ytDev[i].ip == ip) { slot = i; break; } if (ytDev[i].lastMs < ytDev[oldest].lastMs) oldest = i; }
  if (slot < 0) { if (ytDevN < MAX_YT_DEVICES) slot = ytDevN++; else slot = oldest; ytDev[slot] = { ip, 0, 0, 0, 0 }; }
  ytDev[slot].blocked += b; ytDev[slot].skipped += s; ytDev[slot].hidden += h; ytDev[slot].lastMs = millis();
}
static String ytJson() {
  uint32_t ps = dnsblockPausedSeconds();
  String j; j.reserve(300 + ytDevN * 90);
  j += "{\"enabled\":"; j += (ps ? "false" : "true");
  j += ",\"paused_s\":" + String(ps) + ",\"version\":" + String(YT_RULES_VERSION);
  j += ",\"enforce\":"; j += dnsblockYtEnforce() ? "true" : "false"; j += ",\"enforced\":" + String(dnsblockYtEnforced());
  j += ",\"blocked\":" + String(ytBlocked) + ",\"skipped\":" + String(ytSkipped) + ",\"hidden\":" + String(ytHidden) + ",\"reports\":" + String(ytReports);
  j += ",\"devices\":[";
  for (int i = 0; i < ytDevN; i++) {
    if (i) j += ",";
    j += "{\"ip\":\"" + IPAddress(ytDev[i].ip).toString() + "\",\"blocked\":" + String(ytDev[i].blocked) + ",\"skipped\":" + String(ytDev[i].skipped)
       + ",\"hidden\":" + String(ytDev[i].hidden) + ",\"ago_s\":" + String((millis() - ytDev[i].lastMs) / 1000) + "}";
  }
  j += "]}";
  return j;
}
static String ytRulesJson() {
  uint32_t ps = dnsblockPausedSeconds();
  String j; j.reserve(sizeof(YT_RULES_BODY) + 96);
  j += "{\"enabled\":"; j += (ps ? "false" : "true");
  j += ",\"paused_s\":" + String(ps) + ",\"rules\":{\"version\":" + String(YT_RULES_VERSION) + ",";
  j += FPSTR(YT_RULES_BODY); j += "}}";
  return j;
}

// A device that opens YouTube in a browser but never reports extension counts is watching with ads.
// The dashboard lists them; with NTFY_TOPIC set, the phone gets one push per device per boot.
static uint32_t ytNudged[MAX_YT_DEVICES]; static int ytNudgedN = 0; static uint32_t lastNudgeMs = 0;
static void ytNudgeCheck() {
  if (strlen(NTFY_TOPIC) == 0) return;
  uint32_t ips[48], ago[48], ext[48]; int n = dnsblockYtWatchers(ips, ago, ext, 48, 600);
  for (int i = 0; i < n; i++) {
    if (ext[i] < 1800) continue;   // its extension checked in within 30 min
    bool done = false;
    for (int k = 0; k < ytNudgedN; k++) if (ytNudged[k] == ips[i]) done = true;
    if (done || ytNudgedN >= MAX_YT_DEVICES) continue;
    ytNudged[ytNudgedN++] = ips[i];
    notify("YouTube without the ad-free extension",
           IPAddress(ips[i]).toString() + " is watching YouTube in a browser without the extension. Install: http://" + HOSTNAME + ".local/extension");
  }
}

// ---------------- Helpers ----------------
static time_t nowEpoch() { time_t t = time(nullptr); return (t > 1600000000) ? t : 0; }

static void led(uint8_t r, uint8_t g, uint8_t b) {
  rgbLedWrite(RGB_BUILTIN, (uint8_t)(r * LED_BRIGHT / 255), (uint8_t)(g * LED_BRIGHT / 255), (uint8_t)(b * LED_BRIGHT / 255));
}
static void ledForState(NetState s) {
  switch (s) {
    case ST_UP:       led(0, 255, 0);    break;
    case ST_DEGRADED: led(255, 140, 0);  break;
    case ST_DOWN_ISP: led(255, 0, 0);    break;
    case ST_DOWN_LAN: led(255, 0, 80);   break;
    default:          led(0, 0, 255);    break;
  }
}

static String fmtDur(long s) {
  if (s < 60) return String(s) + "s";
  if (s < 3600) return String(s / 60) + "m " + String(s % 60) + "s";
  return String(s / 3600) + "h " + String((s % 3600) / 60) + "m";
}

static String jsonEscape(const String& s) {
  String o; o.reserve(s.length() + 4);
  for (size_t i = 0; i < s.length(); i++) { char c = s[i]; if (c == '"' || c == '\\') o += '\\'; o += c; }
  return o;
}

// Round-trip time of a TCP connect, in ms. -1 on failure.
static int tcpRtt(const IPAddress& ip, uint16_t port) {
  WiFiClient c;
  uint32_t t0 = millis();
  bool ok = c.connect(ip, port, PROBE_TIMEOUT_MS);
  uint32_t dt = millis() - t0;
  c.stop();
  return ok ? (int)dt : -1;
}

// DNS resolution time, in ms. -1 on failure. (May be cached -> ~0 ms; still proves DNS works.)
static int dnsRtt() {
  IPAddress ip;
  uint32_t t0 = millis();
  int ok = WiFi.hostByName("one.one.one.one", ip);
  uint32_t dt = millis() - t0;
  return (ok == 1) ? (int)dt : -1;
}

// Phone notification via ntfy.sh (plain HTTP). No-op if NTFY_TOPIC is empty.
static void notify(const char* title, const String& msg) {
  if (strlen(NTFY_TOPIC) == 0) return;
  HTTPClient http;
  http.setConnectTimeout(3000);
  http.setTimeout(3000);
  http.begin(String("http://ntfy.sh/") + NTFY_TOPIC);
  http.addHeader("Title", title);
  http.addHeader("Tags", "satellite");
  int code = http.POST(msg);
  Serial.printf("[ntfy] %s -> HTTP %d\n", title, code);
  http.end();
}

// ---------------- Probe task (runs on core 0, web server stays responsive on core 1) ----------------
static void probeTask(void*) {
  for (;;) {
    if (WiFi.status() != WL_CONNECTED) {
      xSemaphoreTake(mtx, portMAX_DELAY);
      state = ST_CONNECTING;
      xSemaphoreGive(mtx);
      ledForState(ST_CONNECTING);
      Serial.println("[wifi] disconnected, reconnecting...");
      WiFi.reconnect();
      vTaskDelay(pdMS_TO_TICKS(3000));
      continue;
    }

    uint32_t roundStart = millis();
    int rtt[NT];
    for (int i = 0; i < NT; i++) rtt[i] = tcpRtt(targets[i].ip, targets[i].port);
    int dns = dnsRtt();

    // ---- classify this round ----
    bool gwOk = false, anyPubOk = false, allPubOk = true;
    long sum = 0; int n = 0;
    for (int i = 0; i < NT; i++) {
      bool ok = rtt[i] >= 0;
      if (targets[i].isGateway) { gwOk = ok; }
      else { anyPubOk |= ok; allPubOk &= ok; if (ok) { sum += rtt[i]; n++; } }
    }
    int pubAvg = n ? (int)(sum / n) : -1;

    NetState s;
    if (!gwOk && !anyPubOk)  s = ST_DOWN_LAN;
    else if (!anyPubOk)      s = ST_DOWN_ISP;
    else if (!allPubOk || !gwOk || dns < 0 || pubAvg > DEGRADED_RTT_MS) s = ST_DEGRADED;
    else                     s = ST_UP;
    bool isDown = (s == ST_DOWN_ISP || s == ST_DOWN_LAN);

    // ---- record ----
    bool startedOutage = false, endedOutage = false; long outDur = 0; uint8_t outKind = 0;
    xSemaphoreTake(mtx, portMAX_DELAY);
    for (int i = 0; i < NT; i++) { lastRtt[i] = rtt[i]; if (rtt[i] >= 0) okTotal[i]++; else failTotal[i]++; }
    lastDns = dns;
    Sample& sm = hist[histHead];
    for (int i = 0; i < NT; i++) sm.rtt[i] = (rtt[i] < 0) ? -1 : (int16_t)min(rtt[i], 32000);
    sm.dns = (dns < 0) ? -1 : (int16_t)min(dns, 32000);
    histHead = (histHead + 1) % HISTORY_LEN;
    if (histCount < HISTORY_LEN) histCount++;
    rounds++;

    if (isDown) {
      downStreak++;
      if (downStreak == 1) firstDownEpoch = nowEpoch();
      if (!inOutage && downStreak >= DOWN_DEBOUNCE) {
        inOutage = true; startedOutage = true;
        if (outageCount == MAX_OUTAGES) { memmove(&outages[0], &outages[1], sizeof(Outage) * (MAX_OUTAGES - 1)); outageCount--; }
        outages[outageCount++] = { firstDownEpoch, 0, (uint8_t)s };
      }
    } else {
      downStreak = 0;
      if (inOutage) {
        inOutage = false; endedOutage = true;
        Outage& o = outages[outageCount - 1];
        o.end = nowEpoch();
        outDur = (o.start && o.end) ? (long)(o.end - o.start) : 0;
        outKind = o.kind;
      }
    }
    state = s;
    xSemaphoreGive(mtx);

    // ---- report ----
    ledForState(s);
    Serial.printf("[probe] %-18s | ", STATE_NAMES[s]);
    for (int i = 0; i < NT; i++) Serial.printf("%s=%d ", targets[i].name, rtt[i]);
    Serial.printf("dns=%d  (ms, -1 = fail)\n", dns);

    if (startedOutage) Serial.println("[outage] STARTED");
    if (endedOutage) {
      Serial.printf("[outage] ENDED after %s\n", fmtDur(outDur).c_str());
      notify("Internet is back", "Down for " + fmtDur(outDur) +
             (outKind == ST_DOWN_LAN ? " (router was unreachable)" : " (router was up — ISP/upstream issue)"));
    }

    uint32_t spent = millis() - roundStart;
    if (spent < PROBE_INTERVAL_MS) vTaskDelay(pdMS_TO_TICKS(PROBE_INTERVAL_MS - spent));
  }
}

// ---------------- JSON API ----------------
static String statusJson() {
  String j; j.reserve(1800);
  xSemaphoreTake(mtx, portMAX_DELAY);
  NetState s = state;
  j += "{\"state\":\""; j += STATE_NAMES[s]; j += "\",\"text\":\""; j += STATE_TEXT[s]; j += "\"";
  j += ",\"uptime_s\":" + String(millis() / 1000);
  j += ",\"now\":"  + String((long long)nowEpoch());
  j += ",\"boot\":" + String((long long)bootEpoch);
  j += ",\"rounds\":" + String(rounds);
  j += ",\"interval_ms\":" + String(PROBE_INTERVAL_MS);
  j += ",\"in_outage\":"; j += (inOutage ? "true" : "false");
  j += ",\"ota\":"; j += (strlen(OTA_PASS) ? "true" : "false");
  j += ",\"peers\":["; { String p = PEER_BOARDS; int start = 0; bool first = true;
    while (start < (int)p.length()) { int c = p.indexOf(',', start); if (c < 0) c = p.length(); String ip = p.substring(start, c); ip.trim();
      if (ip.length()) { if (!first) j += ","; j += "\"" + ip + "\""; first = false; } start = c + 1; } }
  j += "]";
  j += ",\"wifi\":{\"ssid\":\"" + jsonEscape(WiFi.SSID()) + "\",\"rssi\":" + String((int)WiFi.RSSI())
     + ",\"ip\":\"" + WiFi.localIP().toString() + "\",\"gw\":\"" + WiFi.gatewayIP().toString()
     + "\",\"host\":\"" + String(HOSTNAME) + ".local\"}";
  j += ",\"targets\":[";
  for (int i = 0; i < NT; i++) {
    long sum = 0; int ok = 0, fail = 0;
    for (int k = 0; k < histCount; k++) {
      int idx = (histHead - histCount + k + HISTORY_LEN) % HISTORY_LEN;
      int v = hist[idx].rtt[i];
      if (v >= 0) { sum += v; ok++; } else fail++;
    }
    int avg = ok ? (int)(sum / ok) : -1;
    int lossPct = (ok + fail) ? (fail * 100) / (ok + fail) : 0;
    if (i) j += ",";
    j += "{\"name\":\"" + String(targets[i].name) + "\",\"host\":\"" + targets[i].ip.toString() + ":" + String((int)targets[i].port)
       + "\",\"rtt\":" + String(lastRtt[i]) + ",\"avg\":" + String(avg) + ",\"loss\":" + String(lossPct)
       + ",\"ok\":" + String(okTotal[i]) + ",\"fail\":" + String(failTotal[i])
       + ",\"gateway\":"; j += (targets[i].isGateway ? "true" : "false"); j += "}";
  }
  j += "],\"dns\":{\"rtt\":" + String(lastDns) + "}";
  j += ",\"outages\":[";
  for (int i = outageCount - 1; i >= 0; i--) {
    if (i != outageCount - 1) j += ",";
    j += "{\"start\":" + String((long long)outages[i].start) + ",\"end\":" + String((long long)outages[i].end)
       + ",\"kind\":\"" + String(STATE_NAMES[outages[i].kind]) + "\"}";
  }
  j += "]}";
  xSemaphoreGive(mtx);
  return j;
}

static String historyJson() {
  String j; j.reserve(HISTORY_LEN * (NT + 1) * 6 + 200);
  xSemaphoreTake(mtx, portMAX_DELAY);
  j += "{\"interval_ms\":" + String(PROBE_INTERVAL_MS) + ",\"count\":" + String(histCount) + ",\"names\":[";
  for (int i = 0; i < NT; i++) { if (i) j += ","; j += "\"" + String(targets[i].name) + "\""; }
  j += "],\"rtt\":[";
  for (int i = 0; i < NT; i++) {
    if (i) j += ",";
    j += "[";
    for (int k = 0; k < histCount; k++) {
      int idx = (histHead - histCount + k + HISTORY_LEN) % HISTORY_LEN;
      if (k) j += ",";
      j += String((int)hist[idx].rtt[i]);
    }
    j += "]";
  }
  j += "],\"dns\":[";
  for (int k = 0; k < histCount; k++) {
    int idx = (histHead - histCount + k + HISTORY_LEN) % HISTORY_LEN;
    if (k) j += ",";
    j += String((int)hist[idx].dns);
  }
  j += "]}";
  xSemaphoreGive(mtx);
  return j;
}



// ---------------- Setup / loop ----------------
void setup() {
  Serial.begin(115200);
#if ARDUINO_USB_CDC_ON_BOOT
  Serial.setTxTimeoutMs(0);   // never stall if no USB terminal is attached
#endif
  delay(300);
  Serial.println("\n[netmon] booting");
  Serial.printf("[mem] heap %u KB free, psram %u KB\n", (unsigned)(ESP.getFreeHeap() / 1024), (unsigned)(ESP.getPsramSize() / 1024));

  mtx = xSemaphoreCreateMutex();
  for (int i = 0; i < NT; i++) { lastRtt[i] = -1; okTotal[i] = failTotal[i] = 0; }
  led(0, 0, 255);

  WiFi.persistent(false);
  WiFi.setHostname(HOSTNAME);
  WiFi.mode(WIFI_STA);
  WiFi.setAutoReconnect(true);
  WiFi.setSleep(false);
  if (strlen(STATIC_IP)) {
    IPAddress ip, gw, mask;
    if (ip.fromString(STATIC_IP) && gw.fromString(STATIC_GW) && mask.fromString(STATIC_MASK)) {
      WiFi.config(ip, gw, mask, IPAddress(1, 1, 1, 1), IPAddress(8, 8, 8, 8));
      Serial.printf("[wifi] using fixed address %s\n", STATIC_IP);
    }
  }
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  Serial.printf("[wifi] connecting to \"%s\" ", WIFI_SSID);

  bool on = false; uint32_t lastReport = millis();
  while (WiFi.status() != WL_CONNECTED) {
    on = !on; led(0, 0, on ? 255 : 0); delay(400); Serial.print(".");
    if (millis() - lastReport > 15000) {
      lastReport = millis();
      Serial.printf("\n[wifi] still connecting, status=%d (1=SSID not found, 4=connect failed/bad password, 6=disconnected)\n", (int)WiFi.status());
    }
  }
  Serial.printf("\n[wifi] connected  ip=%s  gw=%s  rssi=%d dBm\n",
                WiFi.localIP().toString().c_str(), WiFi.gatewayIP().toString().c_str(), (int)WiFi.RSSI());
  for (int i = 0; i < NT; i++) if (targets[i].isGateway) targets[i].ip = WiFi.gatewayIP();

  configTzTime(TZ_INFO, "pool.ntp.org", "time.google.com", "time.cloudflare.com");
  for (int i = 0; i < 40 && nowEpoch() == 0; i++) delay(100);
  bootEpoch = nowEpoch();
  Serial.printf("[time] %s\n", bootEpoch ? "synced" : "not synced yet (will keep trying)");

  if (MDNS.begin(HOSTNAME)) { MDNS.addService("http", "tcp", 80); Serial.printf("[mdns] http://%s.local\n", HOSTNAME); }
  if (strlen(OTA_PASS)) {   // firmware updates over Wi-Fi: [NODE=2] ./build.sh ota
    ArduinoOTA.setMdnsEnabled(false);
    ArduinoOTA.setHostname(HOSTNAME);
    ArduinoOTA.setPassword(OTA_PASS);
    ArduinoOTA.onStart([]() { Serial.println("[ota] update starting"); led(0, 0, 255); });
    ArduinoOTA.onError([](ota_error_t e) { Serial.printf("[ota] error %d\n", (int)e); });
    ArduinoOTA.begin();
    MDNS.enableArduino(3232, true);
    Serial.println("[ota] ready");
  }

  dnsblockBegin();
  prefs.begin("netmon", false);
  dnsblockSetYtEnforce(prefs.getBool("ytEnforce", false));
  dnsblockSetEnabled(prefs.getBool("blocking", true));
  Serial.printf("[adblock] blocking switch is %s\n", dnsblockEnabled() ? "ON" : "OFF (forwarding only)");
  Serial.printf("[ytguard] require-extension switch is %s\n", dnsblockYtEnforce() ? "ON" : "off");

  server.enableCORS(true);   // the dashboard on one board reads the other boards' APIs
  server.on("/",            []() { server.send_P(200, "text/html", INDEX_HTML); });
  server.on("/api/dns",     HTTP_GET,  []() { server.send(200, "application/json", dnsblockJson()); });
  server.on("/api/blocking", HTTP_POST, []() { bool on = server.arg("on") != "0"; dnsblockSetEnabled(on); prefs.putBool("blocking", on); server.send(200, "application/json", on ? "{\"ok\":true,\"enabled\":true}" : "{\"ok\":true,\"enabled\":false}"); });
  server.on("/api/pause",   HTTP_POST, []() { int m = server.arg("min").toInt(); dnsblockPause(m > 0 ? m : 5); server.send(200, "application/json", "{\"ok\":true}"); });
  server.on("/api/resume",  HTTP_POST, []() { dnsblockResume(); server.send(200, "application/json", "{\"ok\":true}"); });
  server.on("/api/update",  HTTP_POST, []() { dnsblockRequestUpdate(); server.send(200, "application/json", "{\"ok\":true}"); });
  server.on("/api/status",  []() { server.send(200, "application/json", statusJson()); });
  server.on("/api/history", []() { server.send(200, "application/json", historyJson()); });
  server.on("/extension",             HTTP_GET, []() { server.send_P(200, "text/html", INSTALL_HTML); });
  server.on("/extension/ytguard.zip", HTTP_GET, []() { server.sendHeader("Content-Disposition", "attachment; filename=\"ytguard.zip\""); server.send_P(200, "application/zip", (PGM_P)YT_EXT_ZIP, YT_EXT_ZIP_LEN); });
  server.on("/api/lists",  HTTP_GET,  []() { server.send(200, "application/json", dnsblockListsJson()); });
  server.on("/api/lists",  HTTP_POST, []() {
    String which = server.arg("list"), add = server.arg("add"), rem = server.arg("remove"), err;
    bool ok = add.length() ? dnsblockListAdd(which.c_str(), add.c_str(), err) : rem.length() ? dnsblockListRemove(which.c_str(), rem.c_str()) : false;
    if (!ok && !err.length()) err = "nothing to do";
    server.send(ok ? 200 : 400, "application/json", ok ? "{\"ok\":true}" : "{\"ok\":false,\"error\":\"" + jsonEscape(err) + "\"}");
  });
  server.on("/api/device", HTTP_POST, []() {   // ?ip=..&name=..  (empty name removes)   ?ip=..&pause=MIN  (0 = resume)
    IPAddress a; if (!a.fromString(server.arg("ip"))) { server.send(400, "application/json", "{\"ok\":false,\"error\":\"bad ip\"}"); return; }
    if (server.hasArg("name"))  dnsblockSetName((uint32_t)a, server.arg("name").c_str());
    if (server.hasArg("pause")) dnsblockPauseDevice((uint32_t)a, (uint32_t)server.arg("pause").toInt());
    server.send(200, "application/json", "{\"ok\":true}");
  });
  server.on("/api/yt",       HTTP_GET,     []() { cors(); server.send(200, "application/json", ytJson()); });
  server.on("/api/yt/rules", HTTP_GET,     []() { dnsblockNoteExtension((uint32_t)server.client().remoteIP()); cors(); server.sendHeader("Cache-Control", "no-cache"); server.send(200, "application/json", ytRulesJson()); });
  server.on("/api/yt/enforce", HTTP_POST,  []() { bool on = server.arg("on") == "1"; dnsblockSetYtEnforce(on); prefs.putBool("ytEnforce", on); cors(); server.send(200, "application/json", on ? "{\"ok\":true,\"enforce\":true}" : "{\"ok\":true,\"enforce\":false}"); });
  server.on("/api/yt/stats", HTTP_OPTIONS, []() { cors(); server.send(204, "text/plain", ""); });
  server.on("/api/yt/stats", HTTP_POST,    []() {
    String body = server.arg("plain");
    dnsblockNoteExtension((uint32_t)server.client().remoteIP());
    ytRecord((uint32_t)server.client().remoteIP(), jsonInt(body, "blocked"), jsonInt(body, "skipped"), jsonInt(body, "hidden"));
    cors(); server.send(200, "application/json", "{\"ok\":true}");
  });
  server.onNotFound(        []() { server.send(404, "text/plain", "not found"); });
  server.begin();
  Serial.printf("[http] dashboard at http://%s/  and  http://%s.local/\n", WiFi.localIP().toString().c_str(), HOSTNAME);

  xTaskCreatePinnedToCore(probeTask, "probe", 8192, nullptr, 1, nullptr, 0);
  notify("netmon online", "Monitoring " + String(WIFI_SSID) + " — dashboard at http://" + HOSTNAME + ".local");
}

void loop() {
  server.handleClient();
  if (strlen(OTA_PASS)) ArduinoOTA.handle();
  if (millis() - lastNudgeMs > 60000UL) { lastNudgeMs = millis(); ytNudgeCheck(); }
  delay(2);
}
